version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: perspective-user-db
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - default
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.3
    restart: unless-stopped
    container_name: perspective-user-pgadmin4
    ports:
      - '${PGADMIN_LISTEN_PORT}:${PG_ADMIN_DEFAULT_PORT}'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - default
    depends_on:
      - db

  app:
    build:
      dockerfile: Dockerfile
    container_name: perspective-user-api
    restart: unless-stopped
    ports:
      - '${API_PORT}:${API_PORT}'
    networks:
      - default
    depends_on:
      - db

networks:
  default:

volumes:
  db-data:
